
version: '3.9'
services:
  psql:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: $ROOT_POSTGRES_USER
      POSTGRES_PASSWORD: $ROOT_POSTGRES_PASSWORD
      DB_NAME: telbot
    env_file:
      - .env
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $ROOT_POSTGRES_USER -d $DB_NAME"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes: 
      - "psql:/var/lib/postgresqlcont/data"
      - "./init.sh:/docker-entrypoint-initdb.d/create_db_user.sh"
  bot:
    container_name: bot
    build:
      context: ./bot
    image: my-bot:latest
    depends_on:
      - psql
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      DB_HOST: psql
      DB_PORT: 5432
      DB_USER: telbot
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: telbot
    links:
      - psql
    volumes:
      - './:/src'
volumes:
  psql:
    driver: local