version: '3.9'

services:
  redis:
    image: redis:6.2.6-alpine
    volumes:
      - 'redis:/data'

  bot:
    container_name: bot
    build:
      context: ./bot
    image: my-bot:latest
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      DB_HOST: redis
      DB_PORT: 6379

volumes:
  redis:

